export type Phase = "A" | "B" | "C" | "D";

export type Step = {
  id: string;
  phase: Phase;
  week: string;
  title: string;
  tool: string;
  details: string;
  done_when: string;
};

export const PHASES: Record<Phase, { title: string; weeks: string; accent: string; light: string; border: string }> = {
  A: { title: "Phase A: Foundation", weeks: "Weeks 1-4", accent: "#2563EB", light: "#EFF6FF", border: "#DBEAFE" },
  B: { title: "Phase B: Build Agents", weeks: "Weeks 5-13", accent: "#D97706", light: "#FFFBEB", border: "#FDE68A" },
  C: { title: "Phase C: Dashboard", weeks: "Weeks 11-20", accent: "#059669", light: "#ECFDF5", border: "#A7F3D0" },
  D: { title: "Phase D: WhatsApp", weeks: "Later", accent: "#6B7280", light: "#F9FAFB", border: "#E5E7EB" },
};

export const STEPS: Step[] = [
  { id: "a1", phase: "A", week: "Week 1", title: "Buy Google Workspace Business Standard", tool: "Browser",
    details: "Go to workspace.google.com. Purchase for 3 users (Selim, Najat, Armaan). $14/user/month = $42/month total. This gives you Gmail, Drive, Calendar under one roof with enterprise controls.",
    done_when: "All 3 users can log in to Gmail and Google Drive" },
  { id: "a2", phase: "A", week: "Week 1", title: "Create Google Shared Drive", tool: "Google Admin Console",
    details: "Admin Console → Apps → Google Workspace → Drive → Sharing settings → enable Shared Drives. Then create a Shared Drive called 'Journey Realty Group'. This is company-owned — files persist when people leave.",
    done_when: "All 3 users see the shared drive in their Drive sidebar" },
  { id: "a3", phase: "A", week: "Week 1", title: "Set up Google Cloud service account with Domain-Wide Delegation", tool: "Google Cloud Console",
    details: "Create a Google Cloud project. Enable Drive API, Gmail API, and Calendar API. Create a service account. Enable Domain-Wide Delegation. Add the required scopes in the Admin Console (Drive: full access, Gmail: modify, Calendar: events). Download the service account JSON key. This is what lets the AI agent access Google services 24/7 without anyone manually logging in.",
    done_when: "You can list Google Drive files using the service account key from a Python script" },
  { id: "a4", phase: "A", week: "Week 1", title: "Set up Google Cloud Pub/Sub for Gmail notifications", tool: "Google Cloud Console",
    details: "Create a Pub/Sub topic and subscription. Configure Gmail to push notifications to this topic when new emails arrive. This is how Gmail tells the agent 'new email arrived' instead of the agent checking Gmail every few minutes.",
    done_when: "Sending a test email triggers a message in your Pub/Sub subscription" },
  { id: "a5", phase: "A", week: "Week 1", title: "Download OneDrive files and start organizing", tool: "Claude Code",
    details: "Get the ~266 MB of files from Selim's OneDrive. Dump everything into one local folder. Use Claude Code to sort files into the designed folder structure: 01_Properties/Brooklyn/The-Evergreen-Bushwick/01_Master-Lease/ etc. Follow the naming convention: YYYY-MM-DD Description v# (no 'final', 'new', 'latest').",
    done_when: "Every file is in the right folder with the right name" },
  { id: "a6", phase: "A", week: "Week 2", title: "Upload organized files to Google Shared Drive", tool: "Claude Code or rclone",
    details: "Upload the clean folder structure to the Journey Realty Group Shared Drive. Create the Inbox-To-Sort folder at the root. Write the rules document (naming conventions, folder structure explanation) and place it at the root of the Drive.",
    done_when: "Selim can browse the shared drive and find any file in under 10 seconds" },
  { id: "a7", phase: "A", week: "Week 2", title: "Walk Selim through the new folder structure", tool: "Screen share or in person",
    details: "Show Selim the complete structure, the naming rules, and most importantly: 'just drop everything in Inbox-To-Sort, the AI agent will file it for you.' Get his feedback. Adjust if needed. This is a critical buy-in moment.",
    done_when: "Selim says 'I get it' and successfully drops a test file in Inbox-To-Sort" },
  { id: "a8", phase: "A", week: "Week 2", title: "Provision Hetzner CX41 VPS", tool: "Hetzner Cloud Console",
    details: "Go to console.hetzner.cloud. Create a CX41 server: 8 vCPU, 16 GB RAM, 160 GB NVMe SSD. Pick Falkenstein or Nuremberg datacenter. ~$16/month. Add your SSH public key during server creation. Choose Ubuntu 24.04.",
    done_when: "You can SSH into the server from your terminal" },
  { id: "a9", phase: "A", week: "Week 2", title: "Harden VPS security + install Coolify", tool: "SSH terminal",
    details: "SSH in and run: (1) Create a non-root user with sudo. (2) Disable root login and password auth in /etc/ssh/sshd_config. (3) Change SSH port to 2222. (4) Set up UFW firewall: allow 2222 (SSH), 80 (HTTP), 443 (HTTPS), deny everything else. (5) Install Coolify: curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash",
    done_when: "Coolify dashboard loads at your-server-ip:8000 and SSH only works on port 2222 with your key" },
  { id: "a10", phase: "A", week: "Week 3", title: "Set up Git repo + Docker Compose + deploy via Coolify", tool: "GitHub + Coolify",
    details: "Create a private GitHub repo for the project. Add docker-compose.yml with all 10 services: PostgreSQL 16, Redis, ClickHouse, MinIO, Langfuse web + worker, LiteLLM, LightRAG, n8n, and the Journey Agent App. Connect Coolify to the GitHub repo. Configure auto-deploy on push to main branch.",
    done_when: "All 10 containers show 'healthy' in the Coolify dashboard" },
  { id: "a11", phase: "A", week: "Week 3", title: "Configure LiteLLM with model routing", tool: "config/litellm_config.yaml",
    details: "Add your Anthropic API key with Sonnet 4.6 as default and Opus 4.6 for complex tasks. Add OpenAI key (GPT-5.4 as fallback). Add Google key (Gemini 2.5 Flash as fallback). Enable prompt caching with 1-hour TTL. Enable spend tracking to PostgreSQL. All agent code will call LiteLLM at http://litellm:4000, never directly to any provider.",
    done_when: "You can curl http://litellm:4000/chat/completions and get a response from Sonnet 4.6" },
  { id: "a12", phase: "A", week: "Week 3", title: "Verify Langfuse tracing works", tool: "Browser",
    details: "Open langfuse.yourdomain.com. Send a test request through LiteLLM. Check that a trace appears in Langfuse showing the model used, token count, latency, and cost. If Langfuse is using too much RAM, you can swap to Langfuse Cloud free tier later — just change one environment variable.",
    done_when: "You see a trace with cost data in the Langfuse web UI" },
  { id: "a13", phase: "A", week: "Week 3", title: "Point domain + set up SSL certificates", tool: "DNS provider + Coolify",
    details: "Create DNS A records pointing to your VPS IP: agent.yourdomain.com, n8n.yourdomain.com, langfuse.yourdomain.com. Coolify's Traefik reverse proxy handles Let's Encrypt SSL certificates automatically.",
    done_when: "All three subdomains load over HTTPS with valid certificates" },
  { id: "a14", phase: "A", week: "Week 4", title: "Deploy LightRAG and ingest all Google Drive files", tool: "LightRAG container + Python",
    details: "Configure LightRAG with PostgreSQL + pgvector backend. Set embedding model to OpenAI text-embedding-3-small ($0.02/MTok). Before ingesting: run Presidio PII scanner on all files. Tier 1 documents (passports, SSNs, bank statements) get BLOCKED from RAG entirely. Tier 2 (leases, rent rolls) get redacted then ingested. Tier 3-4 go in directly. Total embedding cost: ~$0.50.",
    done_when: "You can query 'what does Jean's lease say about pets?' and get a relevant answer" },
  { id: "a15", phase: "A", week: "Week 4", title: "Configure Mem0 inside the Journey Agent App", tool: "Python",
    details: "Mem0 runs as a library inside the main Python application, not as a separate Docker container. Connect it to the same PostgreSQL instance. Set up user_id scoping for Selim and Najat. Test by storing and retrieving a fact: memory.add('Selim prefers Apex for plumbing', user_id='selim') then memory.search('plumbing vendor', user_id='selim').",
    done_when: "You can store and retrieve facts about Selim and Najat" },
  { id: "a16", phase: "A", week: "Week 4", title: "Create Telegram bot + wire up webhook", tool: "Telegram BotFather + Python",
    details: "Message @BotFather on Telegram → /newbot → get the bot token. In the Journey Agent App, add a FastAPI endpoint at /webhook. Register the webhook URL with Telegram. Set up the auth guard: only allow Selim, Najat, and Armaan's Telegram user IDs. Use HTML formatting. Enable arbitrary callback data for inline keyboards.",
    done_when: "You send 'hello' to the bot in Telegram and it responds" },
  { id: "a17", phase: "A", week: "Week 4", title: "Set up nightly backups to Backblaze B2", tool: "Cron + B2 CLI",
    details: "Create a Backblaze B2 bucket (~$0.50/month). Write a backup script that: pg_dump all 4 databases, gzip, upload to B2. Also tar + upload the ClickHouse data directory. Schedule via cron at 3 AM. Keep 7 daily + 4 weekly backups. TEST THE RESTORE — verify the backup actually works.",
    done_when: "You can restore yesterday's backup to a fresh PostgreSQL instance" },

  { id: "b18", phase: "B", week: "Weeks 5-7", title: "Prototype filing workflow in n8n", tool: "n8n",
    details: "Open n8n.yourdomain.com. Build the workflow visually: Google Drive trigger (check Inbox-To-Sort) → download file → send to LLM for classification → determine correct folder → decide filename. Test with real files. Iterate until logic works.",
    done_when: "Drop a receipt in Inbox and n8n correctly identifies it and knows where it should go" },
  { id: "b19", phase: "B", week: "Weeks 5-7", title: "Convert n8n filing workflow to Python with Claude Code", tool: "Claude Code + GSD Framework",
    details: "Export the n8n workflow as JSON. Open Claude Code with GSD framework. Prompt: 'Convert this n8n workflow to a Python module using LangGraph.' Claude Code reads the JSON and writes a LangGraph state graph with: FilingState TypedDict, nodes for fetch→classify→query→decide→move, RetryPolicy on each node, and the wrapper pattern for state isolation.",
    done_when: "The Python module can classify and file a test document correctly" },
  { id: "b20", phase: "B", week: "Weeks 5-7", title: "Add Mem0 + LightRAG disambiguation to filing agent", tool: "Python",
    details: "In the classify node: query LightRAG in hybrid mode ('which property relates to this?') and query Mem0 ('what was Selim discussing recently?'). If confidence > 0.8: auto-file. If < 0.8: interrupt() and ask via Telegram. Write result to Mem0 at completion.",
    done_when: "Agent correctly attributes a receipt to The Evergreen because Selim was discussing it yesterday" },
  { id: "b21", phase: "B", week: "Weeks 5-7", title: "Build the heartbeat scheduler for filing agent", tool: "APScheduler",
    details: "Add AsyncIOScheduler to main.py. Every 20 minutes: call Google Drive API to list Inbox-To-Sort. If new files → invoke filing agent graph. If no new files → return (zero LLM cost). Settings: max_instances=1, coalesce=True. Track seen files in PostgreSQL.",
    done_when: "Dropping a file in Inbox triggers the agent within 20 minutes automatically" },
  { id: "b22", phase: "B", week: "Weeks 5-7", title: "Build Telegram approval flow for uncertain filings", tool: "python-telegram-bot v22.7",
    details: "When unsure: interrupt() pauses graph, saves state. Bot sends Telegram message with inline buttons ('Is this for The Evergreen or Carroll House?'). PTB arbitrary callback data stores full dicts server-side. Button click → Command(resume=answer) wakes graph.",
    done_when: "Selim taps a button and the file gets filed to the correct location" },
  { id: "b23", phase: "B", week: "Weeks 5-7", title: "Shadow deploy the filing agent", tool: "Production VPS",
    details: "Agent processes real files but doesn't move them. Logs what it WOULD do. Sends Selim daily reports. Run 1 week. Track accuracy. Fix mistakes. Goal: >90% accuracy.",
    done_when: "Accuracy above 90% over a full week and Selim trusts the agent" },
  { id: "b24", phase: "B", week: "Weeks 7-9", title: "Build email agent (n8n → Python)", tool: "n8n → Claude Code",
    details: "Gmail Pub/Sub trigger → read email → classify sender → draft response with Mem0/LightRAG context → present for approval. Convert to LangGraph state graph.",
    done_when: "An email from Apex Construction gets a reasonable draft reply" },
  { id: "b25", phase: "B", week: "Weeks 7-9", title: "Build email approval flow in Telegram", tool: "python-telegram-bot",
    details: "Draft shown to Selim with [Approve] [Edit] [Reject] buttons. Tier 2 for routine acks. Tier 3 for money/commitments. Edit flow: Selim types correction, agent revises draft.",
    done_when: "Selim approves an email via Telegram and it sends through Gmail" },
  { id: "b26", phase: "B", week: "Weeks 9-11", title: "Build expense agent", tool: "Claude Code",
    details: "Triggered by filing agent via task_queue. Extracts vendor, amount, date, items from receipt. Logs expense to correct property in PostgreSQL. Uses Mem0 for property attribution.",
    done_when: "Receipt photo → filed + expense logged + Selim notified, all automatically" },
  { id: "b27", phase: "B", week: "Weeks 9-11", title: "Build archive agent", tool: "Claude Code",
    details: "Najat says 'Jean moving out of 3A' → orchestrator → archive agent → create archive folder → present plan → approval → move files → update Mem0. Always Tier 3.",
    done_when: "Tenant move-out workflow works end-to-end via Telegram" },
  { id: "b28", phase: "B", week: "Weeks 9-11", title: "Build orchestrator supervisor graph", tool: "Claude Code",
    details: "Parent StateGraph with supervisor_node. Command routing to filing_wrapper, email_wrapper, expense_wrapper, archive_wrapper. task_queue for cross-agent triggers. Iteration guard (max 10 loops).",
    done_when: "'File this receipt' → orchestrator → filing → expense → notification, all in one flow" },
  { id: "b29", phase: "B", week: "Weeks 11-13", title: "Build morning digest", tool: "APScheduler + python-telegram-bot",
    details: "Per-user job at 8 AM. Selim: pending approvals with buttons, overnight activity, expense snapshot, lease expirations. Najat: tenant comms, expirations, move-outs. Skip if nothing actionable.",
    done_when: "Selim wakes up and sees a useful overnight summary" },
  { id: "b30", phase: "B", week: "Weeks 11-13", title: "Security hardening", tool: "Python + PostgreSQL",
    details: "Agent-specific PostgreSQL roles. Hash-chain audit log (INSERT-only). LLM Guard at proxy boundary. Presidio validation tests. 5 manual prompt injection attempts per agent. Kill switch via /admin emergency.",
    done_when: "Audit log works, PII scanner catches SSNs, injection attempts blocked" },
  { id: "b31", phase: "B", week: "Weeks 11-13", title: "Full production launch", tool: "Everything",
    details: "Shadow mode off. Agents act for real. Monitor for 1 week via Langfuse traces. Fix issues. After one clean week: system is live.",
    done_when: "System runs for a full week with no intervention beyond normal approvals" },

  { id: "c32", phase: "C", week: "Weeks 11-13", title: "Set up Next.js dashboard + deploy to Vercel", tool: "Claude Code",
    details: "Next.js 15 admin template with shadcn/ui + Prisma + Auth.js. Add Tremor charts. Google OAuth. Role-based access (admin/operator/communications). Bottom tab navigation. Deploy to Vercel free tier.",
    done_when: "Dashboard loads at dashboard.yourdomain.com with Google login working on mobile" },
  { id: "c33", phase: "C", week: "Weeks 14-17", title: "Build Dashboard V1: activity feed, approvals, expenses, tenants", tool: "Next.js + shadcn/ui + Tremor",
    details: "Activity feed (SSE timeline), approvals (LangGraph interrupt resume), expense dashboard (Tremor charts), tenant directory (card view mobile, table desktop). Mobile-first.",
    done_when: "Selim sees everything agents did today, approves items, checks expenses — all from his phone" },
  { id: "c34", phase: "C", week: "Weeks 18-20", title: "Build remaining 8 dashboard sections + PWA", tool: "Next.js",
    details: "Vendor directory, property overview, file explorer, knowledge search (cmdk + LightRAG + Mem0), agent status, settings, LLM costs, audit log. PWA manifest for home screen install.",
    done_when: "Najat searches 'when does Jean's lease end?' and gets an answer in the dashboard" },
];
